version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
install:
  - ps: ./Setup.ps1
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: YO9JNl+tIGXyO5L8NRjyl0eI0kJ1mwYFR41a6B2hFdqJ/257Kc92KGzIwp/CdqIg
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
